# Install general programs
winget install Bitwarden.Bitwarden
winget install Upscayl.Upscayl
winget install ShareX.ShareX
winget install Audacity.Audacity
winget install AutoHotkey.AutoHotkey
winget install CPUID.CPU-Z
winget install CPUID.HWMonitor
winget install Discord.Discord
winget install GIMP.GIMP
winget install GitHub.GitHubDesktop
winget install Git.Git
winget install Gyan.FFmpeg
winget install Mozilla.Firefox
winget install Notepad++.Notepad++
winget install Insecure.Npcap
winget install OBSProject.OBSStudio
winget install PrismLauncher.PrismLauncher
winget install Rufus.Rufus
winget install StartIsBack.StartAllBack
winget install Alex313031.Thorium.AVX2
winget install KDE.Kdenlive
winget install qBittorrent.qBittorrent
winget install WinSCP.WinSCP
winget install Microsoft.PowerToys
winget install 7zip.7zip
winget install AdrienAllard.FileConverter
winget install RedHat.VirtViewer
winget install Neovim.Neovim
winget install DuongDieuPhap.ImageGlass
winget install Starship.Starship
winget install Python.Launcher
winget install VideoLAN.VLC
winget install PuTTY.PuTTY
winget install WiresharkFoundation.Wireshark
winget install Microsoft.PowerShell
winget install Famatech.AdvancedIPScanner
winget install Python.Python.3.11